### ISSUE TITLE
External references are not properly resolved using relative location

### ISSUE THREAD

**Issue by anikitin** [SchwarzIT/spectral-intellij-plugin#11] opened 2022-03-31 04:50 UTC
When I use $ref to refer a schema from external file (using relative path) the plugin incorrectly tries to locate this file relatively to "temp" directory, not the directory of main spec file. The expected behavior is described here: [https://swagger.io/docs/specification/using-ref/](https://swagger.io/docs/specification/using-ref/):

> Remote Reference – $ref: 'document.json' Uses the whole document located on the same server and in the same location.
> - The element of the document located in the same folder – $ref: 'document.json#/myElement'
> - The element of the document located in the parent folder – $ref: '../document.json#/myElement'
> - The element of the document located in another folder – $ref: '../another-folder/document.json#/myElement'

See attached file with an example. Plugin displays the error: 
**ENOENT: no such file or directory, open 'c:\Users\....\AppData\Local\Temp\included-openapi.yml'**

Same file is successfully processed with VS Code, Swagger Editor, etc.

[ref-issue.zip](https://github.com/SchwarzIT/spectral-intellij-plugin/files/8386086/ref-issue.zip)

**Comment by markbrockhoff** [comment] 2022-04-04 06:56
Hi @anikitin, thanks for reporting the issue and sorry for the late reply.
The issue is created by a workarround used to persist the currently linted file to disk since by default Jetbrains IDEs do that asynchronously.
We're already aware of this causing a problem when working with split OpenAPI Specs and we're working on a fix for it. But  at the moment, using OpenAPI specs split into multiple files is sadly not supported.

I'll keep this Issue open, and post it here once there's a fix for this problem.

**Closed** 2022-04-04 08:45 UTC
Labels: bug, good first issue

**Comment by anikitin** [comment] 2022-04-04 20:17
Hi @markbrockhoff , my test code seems to work with 1.0.4. At the same time something wrong is happening with the file where I originally caught this problem. Now it seems this file is not handled by Spectral at all -- problems list is empty (while I know there should be problems). And I haven't find anything useful in idea log. Can you point out how to troubleshoot how Spectral plugin works (to see it is really running against the file loaded)? Thanks

**Comment by markbrockhoff** [comment] 2022-04-05 06:34
Hi @anikitin, glad to hear that the issue seems to be fixed. 
About debugging, there is currently no such thing as a debug mode or similar. (But that might be a good idea for a future feature)
Your problem sounds like the glob pattern specified in the spectral settings not matching the file you want to lint. Yo probably already did, but could you make sure it's included in that pattern? If you're still facing the issue, it would be great if you could share some information about your settings and the drectory structure of the files you're trying to lint. A small example for reproduction would also be great.
If all of that does not help, you could clone this repo and run the plugin locally in development mode. Then you'd be able to add additional debug messages or set breakpoints to pin down the problem. But that's of course more of a last resort.
